<?php
/**
 * @file
 * stanford_image.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function stanford_image_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "bean_admin_ui" && $api == "bean") {
    return array("version" => "5");
  }
  list($module, $api) = func_get_args();
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
}
